backend:
  name: github
  repo: ArnaudBan/ange-guepin-ecole-ouverte
  branch: main
media_folder: "medias"
public_folder: "/medias"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "src/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.html"}
      - { label: "Contenu", name: "body", widget: "markdown" }